
Turn 2
================================================================
error: communication error with bot: read failed, errno was: 0 (Success)
Last input received was:


Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 52, in <module>
    cardinals = ship.position.get_all
AttributeError: 'Position' object has no attribute 'get_all'

